name: Build and Publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_firefox:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Use Bun
        uses: oven-sh/setup-bun@v2
      - name: install and build
        working-directory: background
        run: |
          bun install
          bun run build
      - name: Zip firefox
        working-directory: /
        run: zip -qq -r firefox.zip manifest.json background/dist popup icons LICENSE
      - uses: actions/upload-artifact@v4
        with:
          name: firefox
          path: firefox.zip

  publish_firefox:
    needs: build_firefox
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Zip source
        run: zip -qq -r src.zip *
      - name: Download extension
        uses: actions/download-artifact@v4
        with:
          name: firefox
      - name: Publish Firefox
        uses: maoserr/firefox_extension_publish@v1.0.4
        with:
          firefox_extension_id: '{9d7b266a-9484-42d3-a1ef-ec87ee4fa0e1}'
          api_key: ${{ secrets.FIREFOX_API_KEY }}
          api_secret: ${{ secrets.FIREFOX_API_SECRET }}
          file: firefox.zip
          src_file: src.zip
