name: Build and Publish

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - ".github/**"

env:
  MAJOR_VER: 1
  MINOR_VER: 1

jobs:
  build_firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Bun
        uses: oven-sh/setup-bun@v2
      - name: install and build
        working-directory: background
        run: |
          bun install
          ${{ env.MAJOR_VER }}.${{ env.MINOR_VER }}.${{ github.run_number }} bun run build:firefox
      - name: Zip firefox
        run: bun run zip:firefox
      - uses: actions/upload-artifact@v4
        with:
          name: firefox
          path: .output/intra-tweaker-${{ env.MAJOR_VER }}.${{ env.MINOR_VER }}.${{ github.run_number }}-firefox.zip
      - uses: actions/upload-artifact@v4
        with:
          name: source
          path: .output/intra-tweaker-${{ env.MAJOR_VER }}.${{ env.MINOR_VER }}.${{ github.run_number }}-source.zip

  publish_firefox:
    needs: build_firefox
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish Firefox
        uses: wdzeng/firefox-addon@v1
        with:
          addon-guid: "{9d7b266a-9484-42d3-a1ef-ec87ee4fa0e1}"
          jwt-issuer: ${{ secrets.FIREFOX_API_KEY }}
          jwt-secret: ${{ secrets.FIREFOX_API_SECRET }}
          self-hosted: true
          xpi-path: .output/intra-tweaker-${{ env.MAJOR_VER }}.${{ env.MINOR_VER }}.${{ github.run_number }}-firefox.zip
          source-file-path: .output/intra-tweaker-${{ env.MAJOR_VER }}.${{ env.MINOR_VER }}.${{ github.run_number }}-source.zip

  publish_release:
    needs: build_firefox
    runs-on: ubuntu-latest
    steps:
      - name: Download extension
        uses: actions/download-artifact@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.MAJOR_VER }}.${{ env.MINOR_VER }}.${{ github.run_number }}
